version: '3.6'

services:
  web:
    build: .
    restart: always
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: Socialcops
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/SocialCops
    ports:
      - "8000:8000"
 
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - "27019:27017"